baseURL = "https://punipuni21.github.io/punipuni_blog.github.io/"
languageCode = "ja-jp"
weight = 1
title = "chanmitsu55 blog"
publishDir = "public"  # 公開ファイルのディレクトリ名
theme= "hugo_theme_robust" # 使用するテーマ名
hasCJKLanguage = true # 記事のサマリー機能を有効にする。trueにしないと記事サマリーの文章量が大きくなりすぎる。
paginate = 10 # 一つのページに何個まで記事を載せるか。
paginatePath = "page"